### ISSUE TITLE
Content update scheduled

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-OSS-DevOps#22]
This workshop is scheduled for an update. Please review the contents of this repo and comment on this issue with suggested updates. All suggestions must be added to this issue by EOD 11/9/18..

**Comment by fiveisprime** [comment]
I'm still digging into this, but wanted to start adding some thoughts sooner rather than later.

* There's a template to provision both a MySQL database and App Service web app at the same time. It might make more sense to combine the MySQL+webapp steps into one using this template: https://ms.portal.azure.com/#create/Microsoft.WebSiteMySQLDatabase.4.5.0
* Should Jenkins be replaced with Azure Pipelines? It's free and integrates nicely with GitHub, see: https://github.com/marketplace/azure-pipelines I think the model will change though, it would essentially be pipelines for CI (run against PRs) then merges to master trigger a deployment to the staging slot (configured using portal)
* Does it make sense to leverage the Git integration in VS Code or is that invalid for this audience?

**Comment by DawnmarieDesJardins** [comment]
Comments from Dave McKinstry:

Hi Dawnmarie,

Do we have a team room or similar place to collaborate on changes?  For example, it seems to me to be shortsighted to call this “DevOps” when all we really mean “modernizing the exiting app hosting using PaaS and CI/CD with Jenkins.”  I would like to at least add App Insights but don’t want to invest the time if I am the only one who feels this way and the changes would be rejected… Or if someone else is already making those changes in a different branch.

Thanks,
Dave McKinstry
Sr. Program Manager, Azure DevOps Community

**Comment by waltermyersiii** [comment]
@fiveisprime, no we wouldn't replace with Azure Pipelines. We would use Pipelines in the workshop specific to Azure DevOps.

@gfilicetti, agreed on Git. It should always be used on the command line or a person will never understand what it's about.

**Comment by rajanbhayana** [comment]
Can we extend this to following based on common LAMP patterns I have seen in field - 
- use case to use Redis cache as most LAMP website use redis for use sessions or data caching.
- a bit around blobs on how to use azure storage and not shared NAS when moving distributed files to azure PAAS.
- lastly HA. can be a separate exercise, but would be good if solution is spread to at least 2 regions. most of big customers go for multiple regions and are wowed when they see how easy it is to replicate from one region another either on redis, storage or DB. The exercise can start with single region so that things are easy, but later move to a challenge multi region deployment for the more curious ones.
happy to send over a diagram if needed.

**Comment by rajanbhayana** [comment]
Also a word of caution on using wordpress. There are lot of article out there on how wordpress is really slow on azure (and even AWS) due to the way its coded. it does lot of DB trips to fetch data for each request. I have tried it out myself and it wasnt great. There is a big article on how lot of tweaks on azure may speed it up. (https://azure.microsoft.com/sv-se/blog/10-ways-to-speed-up-your-wordpress-site-on-azure-websites/) So as a suggestion, we shouldn't use the word wordpress here but rather something else for code sample. like code samples using laravel framework which is really lightweight and runs on azure. (reference - https://github.com/Azure-Samples/laravel-tasks)

**Comment by DawnmarieDesJardins** [comment]
December 2018 update complete.  QC'd, merged to master and HTML files updated.  Closing issue.
